### ISSUE TITLE
Error: exchange rate error

### ISSUE THREAD

**Issue by TheButterZone** [fordhurley/btc-priceimg#11]
On all images, even ones on your heroku homepage

**Comment by TheButterZone** [comment]
https://twitter.com/BitcoinAverage/status/872523256112320512
"Our v1 API was depreciated 9months ago."

The moving target continues...
https://www.facebook.com/BitcoinAverage/posts/1438041052876868

**Comment by shaun-ba** [comment]
@TheButterZone Yes, we informed as many known users as possible, published to media, our blog etc etc. 

We let v1 run for this length of time to give users plenty of time to migrate code. However, we could not leave it run indefinitely as we have many paying users and v1 endpoints bypass some of the authentication requirement for endpoints.

Hopefully the change here won't take very long at all.

**Comment by shaun-ba** [comment]
untested but test this and submit pull request to the author

```
def get_btc_rate(currency):
    currency = currency.upper()
    url = 'https://api.bitcoinaverage.com/ticker/global/%s/' % currency
    r = requests.get(url)
    r.raise_for_status
    data = r.json()
    per_btc = float(data['24h_avg'])
    return 1.0 / per_btc
```
to

```
def get_btc_rate(currency):
    currency = currency.upper()
    url = 'https://apiv2.bitcoinaverage.com/indices/global/ticker/%s/' % currency
    r = requests.get(url)
    r.raise_for_status
    data = r.json()
    per_btc = float(data['averages']['day'])
    return 1.0 / per_btc
```

**Comment by fordhurley** [comment]
Not sure why, but I didn't get notifications for this. Sorry about that! The fix should be in.
