### ISSUE TITLE
Tracking gifs?

### ISSUE THREAD

**Issue by TheButterZone** [fordhurley/btc-priceimg#5]
Raptor22, site staff at ar15.com, said "Links to tracking .gifs are not allowed on this site. I removed them all. My suggestion is to put the Bitcoin value in parentheses next to the price. Doing this can get you banned."

Why are these tracking gifs?

**Comment by fordhurley** [comment]
I think ar15.com means that they don't allow images that are used for tracking the exchange rate.

**Comment by TheButterZone** [comment]
"
Tracking gifs are small pixel pics that generate revenue for the poster or originator when it is embedded in a thread for a person to click on. Everytime that someone clicks to open it, it generates revenue for either the poster or the original source. The url has specific characteristics that give it away." -Raptor22

/waits to stop being used as a go-between

**Comment by fordhurley** [comment]
Oh, in that case, this isn't one of those. Tell them to look at the code and see for themselves!
