### ISSUE TITLE
Images displaying microtext

### ISSUE THREAD

**Issue by TheButterZone** [fordhurley/btc-priceimg#6]
In all browsers, all devices. http://www.browserstack.com/screenshots/61786baa09343ff26bca7517c2093b5044cd25a3

![2015-03-31 05 08 34](https://cloud.githubusercontent.com/assets/2625857/6912629/2a8b7160-d729-11e4-982f-f0eac0100d02.png)
![screen shot 2015-03-30 at 18 55 06](https://cloud.githubusercontent.com/assets/2625857/6910884/5decad46-d70e-11e4-8599-68e6c42e1383.jpg)

**Comment by TheButterZone** [comment]
s17 on #bitcoin pointed out https://github.com/fordhurley/btc-priceimg/blob/master/priceimg/util.py#L126 but I'm not a coder so IDK what it means.

**Comment by fordhurley** [comment]
Thanks for reporting this. I don't know what caused this to break suddenly, but I had been planning on changing how the images are rendered for a while. This was the much needed motivation to do that! Let me know if you still have the problem.
